- name: Copy Configuration File
  template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml owner=kibana group=kibana mode=0644 force=yes

- name: restart kibana
  service: name=kibana state=restarted enabled=yes

