- name: Copy Master Configuration File
  template: src=elasticsearch.yml.master.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=elasticsearch group=elasticsearch mode=0644 force=yes
  when: es_master_datanode_separate

